### ISSUE TITLE
buffer.py throws error 

### ISSUE THREAD

**Issue by JosephKJ** [optimass/Maximally_Interfered_Retrieval#5] opened 2020-04-16 13:34 UTC
While running the following: 

`python er_main.py --method mir_replay --dataset split_cifar10 --mem_size 50`

the following error occurs:
```
Traceback (most recent call last):
  File "er_main.py", line 178, in <module>
    buffer.add_reservoir(data, target, None, task)
  File "/raid/joseph/Maximally_Interfered_Retrieval/buffer.py", line 130, in add_reservoir
    assert idx_buffer.max() < self.bx.size(0), pdb.set_trace()
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THC/generic/THCTensorMathReduce.cu:85
```

Reason is because `idx_buffer` is coming as empty,  Please see this image:
<img width="1280" alt="Screenshot 2020-04-16 at 5 27 49 PM" src="https://user-images.githubusercontent.com/4231550/79462113-25c54380-8008-11ea-9226-738af5da9973.png">

PyTorch version: 1.4.0

**Comment by JosephKJ** [comment] 2020-04-17 04:32
I am conditionally removing items from the buffer as in this gist: https://gist.github.com/JosephKJ/b557d2303d70ef6ccdcdb61115dad141#file-buffer_modified-py-L129-L143

I get the following result:
```
--------------------------------------
Run #0 Task #4 --> Train Classifier
--------------------------------------


valid:
[[0.87 0.9  0.66 0.58 0.21]
 [0.   0.02 0.53 0.18 0.15]
 [0.   0.   0.22 0.38 0.27]
 [0.   0.   0.   0.77 0.57]
 [0.   0.   0.   0.   0.86]]

test:
[[0.86 0.9  0.68 0.56 0.19]
 [0.   0.02 0.51 0.17 0.13]
 [0.   0.   0.22 0.38 0.24]
 [0.   0.   0.   0.78 0.57]
 [0.   0.   0.   0.   0.87]]
```

Is this an expected accuracy number?

Again, this is the full command:
```
joseph@machine:~/mir$ python er_main.py --method mir_replay --dataset split_cifar10 --mem_size 50
```

**Comment by eugenium** [comment] 2020-04-17 04:44
Which version of pytorch /torchvision are you using?

**Comment by JosephKJ** [comment] 2020-04-17 04:45
torch==1.4.0
torchvision==0.5.0

**Comment by eugenium** [comment] 2020-05-02 20:10
Hi Joseph, where you able to resolve this? I tried running a fresh checkout and didn't encounter this error. I am on torch 1.1.0 which is what we developed with perhaps its a versioning issue, try dropping down to 1.1

**Comment by JosephKJ** [comment] 2020-05-03 04:58
Hi @eugenium, I couldnt resolve this. Can you help me by sharing your current `pip freeze > req.txt`. The current [requirements.txt](https://github.com/optimass/Maximally_Interfered_Retrieval/blob/master/requirements.txt) says PyTorch 1.3. I will try to use your exact configuration.

**Comment by xu-ji** [comment] 2020-05-09 12:28
I think I also may have had this problem at some point, relating to when nothing is sampled from the buffer. I made these changes:
- 4 lines [here](https://github.com/xu-ji/Maximally_Interfered_Retrieval/blob/067e65d9c95da9e663547fcfdf9c9d225a93ac71/mir.py#L360) 
- 1 line [here](https://github.com/xu-ji/Maximally_Interfered_Retrieval/blob/067e65d9c95da9e663547fcfdf9c9d225a93ac71/buffer.py#L132)

**Comment by JosephKJ** [comment] 2020-05-09 13:48
Hi @xu-ji, thanks for your pointers. The changes in the gist that I provided matches well with your changes in `buffer.py`, and the accuracy numbers [here](https://github.com/optimass/Maximally_Interfered_Retrieval/issues/5#issuecomment-615035494), seem to correlate with the number reported in the paper. Hence, I think it is safe to continue with the changes that we both proposed.

**Comment by pclucas14** [comment] 2020-05-09 15:56
Hi, 

so the issue arises when no new samples are added to the buffer and `idx_buffer` has shape `torch.Size([0])`. The assert statement checks if the maximum index added is valid, but pytorch complains because taking the max of an empty tensor throws an error. (so this error is not a pytorch version issue, and the fix presented above is correct). 

As for performance on the second task, this seems to be a feature of the dataset. I've done some [follow-up work](https://github.com/pclucas14/adaptive-quantization-modules) and also observed this issue. 

Let me know if you have other questions. 
-Lucas

**Comment by pclucas14** [comment] 2020-05-09 16:15
(I've pushed the fix on the main branch

**Comment by eugenium** [comment] 2020-05-09 16:44
@pclucas14 were you able to reproduce this error? I didn't get it when running the same command. I did get it in some other circumstances before but usually when the buffer size was very small. Should we update the code with the propose fix?

**Closed** 2020-05-09 16:45 UTC

**Comment by pclucas14** [comment] 2020-05-09 16:52
yes I had the same error on pytorch 1.4
